### ISSUE TITLE
Retexturing clothes

### ISSUE THREAD

**Issue by FoxFire-Starlight** [strakacher21/vrcfox-2.3_body_and_cloth_edition#4]
Is it possible to retexture the clothes? I can't find the material for them. I just want to recolor them and add a few decals.

**Comment by strakacher21** [comment]
Hello, FoxFire-Starlight! There is no texture as such, as **the clothes are made with vertex colors**. 
You can recolor as shown in the images and choose the appropriate UV map if you are going to make a full texture.
_The script combines meshes for optimization in VRC, so be careful with it, if you want to make a separate material in Unity (with textures) purely for one pair of clothes._
![issue_1](https://github.com/user-attachments/assets/bb487cc1-37db-404a-8ebf-143a19cb9db2)
![issue_2](https://github.com/user-attachments/assets/ab61e2f8-491d-4c70-962f-c358deb0565d)
![issue_3](https://github.com/user-attachments/assets/5a809aee-b644-4d75-b28b-24b6d44023f4)
![issue_4](https://github.com/user-attachments/assets/3828cd18-c5b0-49f0-b2bc-7c05d1a43830)
